language: node_js
node_js:
  - 8
  - 10

before_install:
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn test && codecov

deploy:
  provider: npm
  email: ${EMAIL}
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
